/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pi2.views.ui;

/**
 *
 * @author matheus.jmaia
 */
public class TelaVendasUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaVendasUI
     */
    public TelaVendasUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label1 = new javax.swing.JLabel();
        fieldCodProduto = new javax.swing.JTextField();
        botaoAdicionarProduto = new javax.swing.JButton();
        botaoBuscarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldQtdProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaItemVenda = new javax.swing.JTable();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        fieldCPFCliente = new javax.swing.JTextField();
        botatoAddCliente = new javax.swing.JButton();
        botaoBuscarCliente = new javax.swing.JButton();
        BotaoFinalizarVenda = new javax.swing.JButton();
        botaoCancelarVenda = new javax.swing.JButton();

        setTitle("Nova Venda");

        Label1.setText("Código do produto: ");

        fieldCodProduto.setToolTipText("Código do produto");

        botaoAdicionarProduto.setText("Adicionar");
        botaoAdicionarProduto.setToolTipText("Adiciona o produto ao carrinho");

        botaoBuscarProduto.setText("Pesquisar produto");
        botaoBuscarProduto.setToolTipText("Busca determinado produto e seu código");
        botaoBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade:");
        jLabel1.setToolTipText("");

        fieldQtdProduto.setToolTipText("Especifica a quantidade de um produto, caso vazio a quantidade será um por padrão ");

        TabelaItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Qtde", "Valor UN", "Valor Item"
            }
        ));
        jScrollPane1.setViewportView(TabelaItemVenda);

        label2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        label2.setText("Valor Total: R$");

        label3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        label3.setText("0.0");

        label4.setText("CPF do cliente:");

        fieldCPFCliente.setToolTipText("Código do produto");
        fieldCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCPFClienteActionPerformed(evt);
            }
        });

        botatoAddCliente.setText("Adicionar cliente");
        botatoAddCliente.setToolTipText("Adiciona o cliente a venda");
        botatoAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botatoAddClienteActionPerformed(evt);
            }
        });

        botaoBuscarCliente.setText("Pesquisar cliente");
        botaoBuscarCliente.setToolTipText("Permite pesquisar um cliente por nome ou outros.");
        botaoBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarClienteActionPerformed(evt);
            }
        });

        BotaoFinalizarVenda.setText("Finalizar compra");
        BotaoFinalizarVenda.setToolTipText("Finaliza a venda");

        botaoCancelarVenda.setText("Cancelar");
        botaoCancelarVenda.setToolTipText("Cancela a compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoAdicionarProduto)
                        .addGap(119, 119, 119)
                        .addComponent(botaoBuscarProduto))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(label2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botatoAddCliente)
                                .addGap(233, 233, 233)))
                        .addComponent(botaoBuscarCliente)))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCancelarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoFinalizarVenda)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1)
                    .addComponent(fieldCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(fieldQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarProduto)
                    .addComponent(botaoBuscarProduto))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4)
                    .addComponent(fieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botatoAddCliente)
                    .addComponent(botaoBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarVenda)
                    .addComponent(BotaoFinalizarVenda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoBuscarClienteActionPerformed

    private void fieldCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCPFClienteActionPerformed

    private void botaoBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoBuscarProdutoActionPerformed

    private void botatoAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botatoAddClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botatoAddClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFinalizarVenda;
    private javax.swing.JLabel Label1;
    private javax.swing.JTable TabelaItemVenda;
    private javax.swing.JButton botaoAdicionarProduto;
    private javax.swing.JButton botaoBuscarCliente;
    private javax.swing.JButton botaoBuscarProduto;
    private javax.swing.JButton botaoCancelarVenda;
    private javax.swing.JButton botatoAddCliente;
    private javax.swing.JTextField fieldCPFCliente;
    private javax.swing.JTextField fieldCodProduto;
    private javax.swing.JTextField fieldQtdProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    // End of variables declaration//GEN-END:variables
}
